language: node_js
node_js:
  - 10
script:
  - npm version
  - npm run lint
  - npm run build
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
cache:
  directories:
    - $HOME/.npm
    - node_modules